### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by 0xshubhs** [KaalaDaaku/Callback-Hell#1]
**As  Javascript's synchronous nature(basically using nested `setTimeout`) leads to callback hell , it's asynchronous nature(`Promises` and `async-await`) makes the javascript runtime to avoid the callbackHell**

### Kindly update the Readme

**Comment by rohanmaurya-766** [comment]
Okay, I understand now! 
Thank you for reviewing and correcting my mistakes
Senpai ^_^

**Comment by 0xshubhs** [comment]
**That's what we do !!**


## I'm now closing this issue!!!!
